[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/marhalaty/artisan queue:work database --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/laravel-worker.log
stopwaitsecs=3600
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",HOME="/root",LOGNAME="root"

# Optional: For monitoring
# monitor=TICK_60  # Check worker health every 60 seconds
